In [81]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/customer-churn-dataset/customer_churn_dataset-testing-master.csv
/kaggle/input/customer-churn-dataset/customer_churn_dataset-training-master.csv

In [82]:
df=pd.read_csv('/kaggle/input/customer-churn-dataset/customer_churn_dataset-training-master.csv')

In [83]:
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [84]:
df.isnull().sum()

CustomerID           1
Age                  1
Gender               1
Tenure               1
Usage Frequency      1
Support Calls        1
Payment Delay        1
Subscription Type    1
Contract Length      1
Total Spend          1
Last Interaction     1
Churn                1
dtype: int64

In [85]:
df.duplicated().sum()

0

In [86]:
df['Churn'].value_counts()

Churn
1.0    249999
0.0    190833
Name: count, dtype: int64

In [87]:
df.drop(columns=['CustomerID'], inplace=True)

In [88]:
df.head()

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Age                440832 non-null  float64
 1   Gender             440832 non-null  object
 2   Tenure             440832 non-null  float64
 3   Usage Frequency    440832 non-null  float64
 4   Support Calls      440832 non-null  float64
 5   Payment Delay      440832 non-null  float64
 6   Subscription Type  440832 non-null  object
 7   Contract Length    440832 non-null  object
 8   Total Spend        440832 non-null  float64
 9   Last Interaction   440832 non-null  float64
 10  Churn              440832 non-null  float64
dtypes: float64(8), object(3)
memory usage: 37.0+ MB

In [90]:
df['Support Calls'].value_counts()

Support Calls
0.0     69875
1.0     69476
2.0     66571
3.0     52729
4.0     38750
5.0     24918
10.0    23900
7.0     23870
9.0     23630
8.0     23559
6.0     23554
Name: count, dtype: int64

In [91]:
df.isnull().sum()

Age                  1
Gender               1
Tenure               1
Usage Frequency      1
Support Calls        1
Payment Delay        1
Subscription Type    1
Contract Length      1
Total Spend          1
Last Interaction     1
Churn                1
dtype: int64

In [92]:
df=df.dropna(axis=0)

In [93]:
df.isnull().sum()

Age                  0
Gender               0
Tenure               0
Usage Frequency      0
Support Calls        0
Payment Delay        0
Subscription Type    0
Contract Length      0
Total Spend          0
Last Interaction     0
Churn                0
dtype: int64

In [94]:
df.head()

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [95]:
df=pd.get_dummies(df,columns=['Gender','Subscription Type','Contract Length'], drop_first=True, dtype=int)

In [96]:
df_test.head()

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn,Gender_Male,Subscription Type_Premium,Subscription Type_Standard,Contract Length_Monthly,Contract Length_Quarterly
0,1,22,25,14,4,27,598,9,1,0,0,0,1,0
1,2,41,28,28,7,13,584,20,0,0,0,1,1,0
2,3,47,27,10,2,29,757,21,0,1,1,0,0,0
3,4,35,9,12,5,17,232,18,0,1,1,0,0,1
4,5,53,58,24,9,2,533,18,0,0,0,1,0,0

In [97]:
df

,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn,Gender_Male,Subscription Type_Premium,Subscription Type_Standard,Contract Length_Monthly,Contract Length_Quarterly
0,30.0,39.0,14.0,5.0,18.0,932.00,17.0,1.0,0,0,1,0,0
1,65.0,49.0,1.0,10.0,8.0,557.00,6.0,1.0,0,0,0,1,0
2,55.0,14.0,4.0,6.0,18.0,185.00,3.0,1.0,0,0,0,0,1
3,58.0,38.0,21.0,7.0,7.0,396.00,29.0,1.0,1,0,1,1,0
4,23.0,32.0,20.0,5.0,8.0,617.00,20.0,1.0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
440828,42.0,54.0,15.0,1.0,3.0,716.38,8.0,0.0,1,1,0,0,0
440829,25.0,8.0,13.0,1.0,20.0,745.38,2.0,0.0,0,1,0,0,0
440830,26.0,35.0,27.0,1.0,5.0,977.31,9.0,0.0,1,0,1,0,1
440831,28.0,55.0,14.0,2.0,0.0,602.55,2.0,0.0,1,0,1,0,1
440832,31.0,48.0,20.0,1.0,14.0,567.77,21.0,0.0,1,1,0,0,1

In [98]:
x=df.drop(columns=['Churn'])
y=df['Churn']

In [99]:
df_test

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn,Gender_Male,Subscription Type_Premium,Subscription Type_Standard,Contract Length_Monthly,Contract Length_Quarterly
0,1,22,25,14,4,27,598,9,1,0,0,0,1,0
1,2,41,28,28,7,13,584,20,0,0,0,1,1,0
2,3,47,27,10,2,29,757,21,0,1,1,0,0,0
3,4,35,9,12,5,17,232,18,0,1,1,0,0,1
4,5,53,58,24,9,2,533,18,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64369,64370,45,33,12,6,21,947,14,1,0,0,0,0,1
64370,64371,37,6,1,5,22,923,9,1,1,0,1,0,0
64371,64372,25,39,14,8,30,327,20,1,1,1,0,1,0
64372,64373,50,18,19,7,22,540,13,1,0,0,1,1,0
64373,64374,52,45,15,9,25,696,22,1,0,0,1,1,0

In [116]:
df_test=pd.read_csv('/kaggle/input/customer-churn-dataset/customer_churn_dataset-testing-master.csv')
df_test=pd.get_dummies(df_test,columns=['Gender','Subscription Type','Contract Length'], drop_first=True, dtype=int)

In [117]:
x_test=df_test.drop(columns=['Churn','CustomerID'])
y_test=df_test['Churn']

In [118]:
df

,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn,Gender_Male,Subscription Type_Premium,Subscription Type_Standard,Contract Length_Monthly,Contract Length_Quarterly
0,30.0,39.0,14.0,5.0,18.0,932.00,17.0,1.0,0,0,1,0,0
1,65.0,49.0,1.0,10.0,8.0,557.00,6.0,1.0,0,0,0,1,0
2,55.0,14.0,4.0,6.0,18.0,185.00,3.0,1.0,0,0,0,0,1
3,58.0,38.0,21.0,7.0,7.0,396.00,29.0,1.0,1,0,1,1,0
4,23.0,32.0,20.0,5.0,8.0,617.00,20.0,1.0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
440828,42.0,54.0,15.0,1.0,3.0,716.38,8.0,0.0,1,1,0,0,0
440829,25.0,8.0,13.0,1.0,20.0,745.38,2.0,0.0,0,1,0,0,0
440830,26.0,35.0,27.0,1.0,5.0,977.31,9.0,0.0,1,0,1,0,1
440831,28.0,55.0,14.0,2.0,0.0,602.55,2.0,0.0,1,0,1,0,1
440832,31.0,48.0,20.0,1.0,14.0,567.77,21.0,0.0,1,1,0,0,1

In [103]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

x_train_scaled=scaler.fit_transform(x)
x_test_scaled=scaler.fit(x_test)

In [122]:
x_test_scaled=scaler.fit_transform(x_test)

In [123]:
x_test_scaled

array([[-1.43420211, -0.40909964, -0.12252553, ..., -0.70819451,
         1.38163018, -0.69173877],
       [-0.0697304 , -0.23364156,  1.46542392, ...,  1.41204144,
         1.38163018, -0.69173877],
       [ 0.36115541, -0.29212759, -0.57622537, ..., -0.70819451,
        -0.72378269, -0.69173877],
       ...,
       [-1.21875921,  0.40970473, -0.12252553, ..., -0.70819451,
         1.38163018, -0.69173877],
       [ 0.57659831, -0.81850183,  0.44459927, ...,  1.41204144,
         1.38163018, -0.69173877],
       [ 0.72022691,  0.76062088, -0.00910057, ...,  1.41204144,
         1.38163018, -0.69173877]])

In [121]:
x_test

,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Gender_Male,Subscription Type_Premium,Subscription Type_Standard,Contract Length_Monthly,Contract Length_Quarterly
0,22,25,14,4,27,598,9,0,0,0,1,0
1,41,28,28,7,13,584,20,0,0,1,1,0
2,47,27,10,2,29,757,21,1,1,0,0,0
3,35,9,12,5,17,232,18,1,1,0,0,1
4,53,58,24,9,2,533,18,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
64369,45,33,12,6,21,947,14,0,0,0,0,1
64370,37,6,1,5,22,923,9,1,0,1,0,0
64371,25,39,14,8,30,327,20,1,1,0,1,0
64372,50,18,19,7,22,540,13,0,0,1,1,0
64373,52,45,15,9,25,696,22,0,0,1,1,0

In [104]:
import tensorflow 
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [105]:
model = Sequential()
model.add(Dense(3,activation='sigmoid',input_dim=12))
model.add(Dense(1,activation='sigmoid',))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [106]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_7 (Dense)                      │ (None, 3)                   │              39 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 43 (172.00 B)

 Trainable params: 43 (172.00 B)

 Non-trainable params: 0 (0.00 B)

In [107]:
model.compile(loss='binary_crossentropy',optimizer='Adam')

In [108]:
x_train_scaled

array([[-0.7533263 ,  0.44875958, -0.21051068, ...,  1.39859379,
        -0.4962315 , -0.81725773],
       [ 2.05964592,  1.02827797, -1.7245625 , ..., -0.71500389,
         2.01518847, -0.81725773],
       [ 1.25593957, -1.00003639, -1.37516593, ..., -0.71500389,
        -0.4962315 ,  1.22360421],
       ...,
       [-1.07480884,  0.21695223,  1.30354113, ...,  1.39859379,
        -0.4962315 ,  1.22360421],
       [-0.91406757,  1.37598901, -0.21051068, ...,  1.39859379,
        -0.4962315 ,  1.22360421],
       [-0.67295566,  0.97032613,  0.48828246, ..., -0.71500389,
        -0.4962315 ,  1.22360421]])

In [109]:
model.fit(x_train_scaled,y,epochs=10)

Epoch 1/10
13776/13776 ━━━━━━━━━━━━━━━━━━━━ 14s 992us/step - loss: 0.4108
Epoch 2/10
13776/13776 ━━━━━━━━━━━━━━━━━━━━ 14s 1ms/step - loss: 0.2206
Epoch 3/10
13776/13776 ━━━━━━━━━━━━━━━━━━━━ 14s 993us/step - loss: 0.1966
Epoch 4/10
13776/13776 ━━━━━━━━━━━━━━━━━━━━ 14s 1ms/step - loss: 0.1745
Epoch 5/10
13776/13776 ━━━━━━━━━━━━━━━━━━━━ 14s 992us/step - loss: 0.1552
Epoch 6/10
13776/13776 ━━━━━━━━━━━━━━━━━━━━ 14s 988us/step - loss: 0.1430
Epoch 7/10
13776/13776 ━━━━━━━━━━━━━━━━━━━━ 14s 1ms/step - loss: 0.1358
Epoch 8/10
13776/13776 ━━━━━━━━━━━━━━━━━━━━ 14s 998us/step - loss: 0.1308
Epoch 9/10
13776/13776 ━━━━━━━━━━━━━━━━━━━━ 14s 1ms/step - loss: 0.1263
Epoch 10/10
13776/13776 ━━━━━━━━━━━━━━━━━━━━ 14s 989us/step - loss: 0.1236

In [110]:
model.layers[0].get_weights()

[array([[ 1.3224739e-01, -8.1052876e+00,  5.6502924e+00],
        [ 1.0998964e-01,  9.0534031e-02,  9.0240151e-02],
        [ 5.4397095e-02,  9.1751873e-02,  9.5197208e-02],
        [-4.1451596e-02,  1.6732436e-01, -1.3659234e+01],
        [-9.1273963e-01, -7.7166480e-01, -7.1562576e-01],
        [ 6.0754452e+00, -2.5296307e-01, -2.4339531e-01],
        [-4.8204479e-01, -4.1491058e-01, -4.1282865e-01],
        [ 5.2520585e-01,  4.5340502e-01,  3.7774605e-01],
        [ 1.1542449e-01,  4.4334173e-02,  6.0799615e-03],
        [ 2.7121186e-02,  9.0618230e-02,  2.3743547e-02],
        [-5.3706908e+00, -7.9837990e+00, -5.7233400e+00],
        [ 1.6698815e-03, -2.1557551e-02, -3.0928545e-02]], dtype=float32),
 array([1.3449241 , 4.1295347 , 0.00828962], dtype=float32)]

In [112]:
model.layers[1].get_weights()

[array([[-6.1129236],
        [-5.9886827],
        [-6.8747954]], dtype=float32),
 array([15.958792], dtype=float32)]

In [130]:
df_test.shape

(64374, 14)

In [131]:
x_test_scaled.shape

(64374, 12)

In [132]:
y_test.shape

(64374,)

In [133]:
y_log=model.predict(x_test_scaled)

2012/2012 ━━━━━━━━━━━━━━━━━━━━ 2s 897us/step

In [134]:
y_pred=np.where(y_log>0.5,1,0)

In [135]:
y_pred.shape

(64374, 1)

In [136]:
from sklearn.metrics import  accuracy_score
accuracy_score(y_pred,y_test)

0.5900208158573337